version: '2'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis:/data
        # command: redis-server --appendonly yes
  app:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - postgres
      - redis
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/jphacks
